/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDnsRecordDto { 
    /**
     * The unique id of Healthcheck in UptimeKuma
     */
    healthCheckId: number;
    /**
     * The domain name
     */
    name: string;
    /**
     * The primary IPv4 address
     */
    primaryIp4: string;
    /**
     * The backup IPv4 address
     */
    backupIp4: string;
    /**
     * The primary IPv6 address
     */
    primaryIp6: string;
    /**
     * The backup IPv6 address
     */
    backupIp6: string;
    /**
     * The Cloudflare API token for this zone
     */
    apiToken: string;
    /**
     * Password / Secret - Key to edit policy
     */
    secret: string;
}

