/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DnsRecordsDto } from './dnsRecordsDto';
import { NameServerInfoDto } from './nameServerInfoDto';
import { WhoisDataDto } from './whoisDataDto';


export interface DnsLookupOutputDto { 
    /**
     * Domain name that was queried
     */
    domain: string;
    /**
     * List of nameservers with query status
     */
    nameservers: Array<NameServerInfoDto>;
    /**
     * Nameserver used for the DNS queries
     */
    selectedNameserver: string;
    /**
     * DNS records grouped by type
     */
    records: DnsRecordsDto;
    /**
     * WHOIS information for the domain
     */
    whoisData: WhoisDataDto;
    /**
     * DNS resolver used for the query
     */
    usedResolver: DnsLookupOutputDto.UsedResolverEnum;
}
export namespace DnsLookupOutputDto {
    export type UsedResolverEnum = 'Cloudflare' | 'Google' | 'Quad9' | 'AdGuard' | 'Cisco';
    export const UsedResolverEnum = {
        Cloudflare: 'Cloudflare' as UsedResolverEnum,
        Google: 'Google' as UsedResolverEnum,
        Quad9: 'Quad9' as UsedResolverEnum,
        AdGuard: 'AdGuard' as UsedResolverEnum,
        Cisco: 'Cisco' as UsedResolverEnum
    };
}


