/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DnsRecordDto } from './dnsRecordDto';


export interface DnsRecordsDto { 
    a: Array<DnsRecordDto>;
    aaaa: Array<DnsRecordDto>;
    cname: Array<DnsRecordDto>;
    txt: Array<DnsRecordDto>;
    mx: Array<DnsRecordDto>;
    ns: Array<DnsRecordDto>;
}

