/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DnsRecordDtoValue } from './dnsRecordDtoValue';


export interface DnsRecordDto { 
    /**
     * Type of DNS record (A, AAAA, CNAME, etc.)
     */
    type: string;
    value: DnsRecordDtoValue;
    /**
     * Time to live in seconds
     */
    ttl?: number;
}

