/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Value of the DNS record
 */
/**
 * @type DnsRecordDtoValue
 * Value of the DNS record
 * @export
 */
export type DnsRecordDtoValue = Array<string> | string;

