/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NameServerInfoDto { 
    /**
     * DNS server hostname
     */
    server: string;
    /**
     * Indicates if this nameserver was used for the current query
     */
    isUsedForQuery: boolean;
}

