/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UptimeKumaHeartbeatDto { 
    /**
     * Monitor ID
     */
    monitorID: number;
    /**
     * Status code
     */
    status: number;
    /**
     * Timestamp of the heartbeat
     */
    time: string;
    /**
     * Status message
     */
    msg: string;
    /**
     * Importance flag
     */
    important: boolean;
    /**
     * Duration in seconds
     */
    duration: number;
    /**
     * Timezone name
     */
    timezone: string;
    /**
     * Timezone offset
     */
    timezoneOffset: string;
    /**
     * Local date time
     */
    localDateTime: string;
}

