/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UptimeKumaMonitorDto { 
    /**
     * Monitor ID
     */
    id: number;
    /**
     * Monitor name
     */
    name: string;
    /**
     * Monitor description
     */
    description: object;
    /**
     * Path name
     */
    pathName: string;
    /**
     * Parent monitor
     */
    parent: object;
    /**
     * Child monitor IDs
     */
    childrenIDs: Array<string>;
    /**
     * URL to monitor
     */
    url: string;
    /**
     * HTTP method
     */
    method: string;
    /**
     * Hostname
     */
    hostname: object;
    /**
     * Port number
     */
    port: object;
    /**
     * Maximum retries
     */
    maxretries: number;
    /**
     * Monitor weight
     */
    weight: number;
    /**
     * Active status
     */
    active: boolean;
    /**
     * Force inactive status
     */
    forceInactive: boolean;
    /**
     * Monitor type
     */
    type: string;
    /**
     * Timeout in seconds
     */
    timeout: number;
    /**
     * Check interval
     */
    interval: number;
    /**
     * Tags associated with monitor
     */
    tags: Array<string>;
    /**
     * Accepted status codes
     */
    accepted_statuscodes: Array<string>;
}

