/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserAgentInfoDto { 
    /**
     * Browser name
     */
    browser: string;
    /**
     * Browser version
     */
    version: string;
    /**
     * Operating system
     */
    os: string;
    /**
     * Device type
     */
    device: string;
}

