/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAgentInfoDto } from './userAgentInfoDto';
import { LocationInfoDto } from './locationInfoDto';


export interface VisitorInfoResponseDto { 
    /**
     * IP address of the visitor
     */
    ipAddress: string;
    /**
     * Fully Qualified Domain Name
     */
    fqdn?: object | null;
    /**
     * Internet Service Provider
     */
    isp?: object | null;
    /**
     * Raw user agent string
     */
    userAgent: string;
    /**
     * Formatted user agent information
     */
    userAgentInfo: UserAgentInfoDto;
    /**
     * Geographic location information
     */
    location?: LocationInfoDto | null;
    /**
     * Timestamp of the request
     */
    timestamp: string;
}

