/**
 * SYS-HUB - REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WhoisDataDto { 
    /**
     * List of authoritative nameservers
     */
    nameservers: Array<string>;
    /**
     * Domain registrar name
     */
    registrar?: string;
    /**
     * Domain creation date
     */
    creationDate?: string;
    /**
     * Domain expiration date
     */
    expirationDate?: string;
}

